# Generated by Django 3.2.7 on 2021-09-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCompare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='app.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='app.currency')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='compared_currencies',
            field=models.ManyToManyField(related_name='compared_to', through='app.CurrencyCompare', to='app.Currency'),
        ),
    ]
